AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: My First Go Lambda Function
Resources:
  LambdaFunctionUsingGo:
    Type: AWS::Serverless::Function
    Properties:
      Handler: main
      Runtime: go1.x
      CodeUri: .
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: /test
            Method: post